### ISSUE TITLE
Running example from script

### ISSUE THREAD

**Issue by nachovoss** [zblesk/csv-to-sqlite#13]
When trying to run from script with your example I get the following error:

Traceback (most recent call last):
  File "D:/webs/pierre/pruebas1lite.py", line 4, in <module>
    options = csv_to_sqlite.CsvOptions(typing_style="full", encoding="windows-1250")
TypeError: __init__() got an unexpected keyword argument 'encoding'

If i remove the encoding then i get this other error:

Traceback (most recent call last):
  File "D:/webs/pierre/pruebas1lite.py", line 6, in <module>
    csv_to_sqlite.write_csv(input_files, "D:/webs/output.db", options)
AttributeError: module 'csv_to_sqlite' has no attribute 'write_csv'

some help would be much appriciated

**Comment by zblesk** [comment]
Hello.
That was a feature that was already written, but not released yet. 
It was released 10 minutes ago. 

Please try updating (the new version is 2.1.0) and tell me if it fixed the problem.

**Comment by nachovoss** [comment]
Hey thanks for your quick reply, 

It's working if I run the file from command line,

but  I'm getting this error when running from IDLE:

Traceback (most recent call last):
  File "D:\webs\pierre\pruebas1lite.py", line 8, in <module>
    csv_to_sqlite.write_csv(input_files, "output.sqlite", options
  File "C:\Users\Nacho\AppData\Local\Programs\Python\Python37\lib\site-packages\csv_to_sqlite.py", line 200, in write_csv
    with click.progressbar(files) as _files:
  File "C:\Users\Nacho\AppData\Local\Programs\Python\Python37\lib\site-packages\click\termui.py", line 351, in progressbar
    width=width, color=color)
  File "C:\Users\Nacho\AppData\Local\Programs\Python\Python37\lib\site-packages\click\_termui_impl.py", line 70, in __init__
    file = _default_text_stdout()
  File "C:\Users\Nacho\AppData\Local\Programs\Python\Python37\lib\site-packages\click\_compat.py", line 675, in func
    rv = wrapper_func()
  File "C:\Users\Nacho\AppData\Local\Programs\Python\Python37\lib\site-packages\click\_compat.py", line 436, in get_text_stdout
    rv = _get_windows_console_stream(sys.stdout, encoding, errors)
  File "C:\Users\Nacho\AppData\Local\Programs\Python\Python37\lib\site-packages\click\_winconsole.py", line 295, in _get_windows_console_stream
    func = _stream_factories.get(f.fileno())
io.UnsupportedOperation: fileno

**Comment by zblesk** [comment]
Hm, maybe some issue with Click? 🤔 Not sure. 

Could you post your code and preferably also a csv file the code will crash on?

**Comment by zblesk** [comment]
No point in keeping this open, I guess.
